import Link from "next/link";
import { redirect } from "next/navigation";
import { getAdminSession } from "@/lib/auth";
import { getDossiers } from "@/lib/data";
import { displayDate, gradeLabels } from "@/lib/types";
import { logout, deleteDossier, publishDossier } from "@/app/actions";
import { ConfirmForm } from "@/components/admin-actions";
import { LocalDate } from "@/components/local-date";

export const dynamic = "force-dynamic";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ message?: string; q?: string; status?: string }> }) {
  if (!(await getAdminSession())) redirect("/admin/login");
  const params = await searchParams;
  const allDossiers = await getDossiers({ includeDrafts: true });
  const dossiers = allDossiers.filter((dossier) => (!params.status || dossier.status === params.status) && (!params.q || dossier.title.toLowerCase().includes(params.q.toLowerCase())));
  return <main className="admin-shell"><header className="admin-top"><div><span className="kicker">Corrigo / private desk</span><h1>Evidence files</h1><p className="admin-count">{allDossiers.length} total · {dossiers.length} shown</p></div><div className="admin-actions"><Link className="admin-button" href="/admin/evidence/new">+ New dossier</Link><form action={logout}><button className="admin-button secondary" type="submit">Sign out</button></form></div></header>{params.message && <p className="success">{params.message === "database-needed" ? "Connect DATABASE_URL to save dossiers." : params.message === "schedule-must-be-in-the-future" ? "Choose a future date and time for scheduling." : `Dossier ${params.message}.`}</p>}<form className="admin-filters" action="/admin"><input name="q" defaultValue={params.q} placeholder="Search titles" aria-label="Search dossier titles" /><select name="status" defaultValue={params.status || ""} aria-label="Filter by status"><option value="">All statuses</option><option value="DRAFT">Draft</option><option value="SCHEDULED">Scheduled</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select><button className="admin-button secondary" type="submit">Filter</button>{(params.q || params.status) && <Link className="admin-button secondary" href="/admin">Clear</Link>}</form><div className="admin-table">{dossiers.length ? dossiers.map((dossier) => <div className="admin-row" key={dossier.id}><div className="admin-title"><Link href={`/admin/evidence/${dossier.id}/edit`}>{dossier.title}</Link><small>{dossier.slug}</small></div><small className={`status status-${dossier.status.toLowerCase()}`}>{gradeLabels[dossier.grade]} · {dossier.status.toLowerCase()}{dossier.scheduledAt ? <><br />Scheduled <LocalDate date={dossier.scheduledAt} /></> : ""}</small><small>{displayDate(dossier.reviewedAt)}</small><div className="admin-actions"><Link className="admin-button secondary" href={`/admin/evidence/${dossier.id}/edit`}>Edit</Link><Link className="admin-button secondary" href={`/evidence/${dossier.slug}${dossier.status === "PUBLISHED" ? "" : "?preview=1"}`}>View</Link>{dossier.status !== "PUBLISHED" && <ConfirmForm action={publishDossier} message="Publish this dossier now? It will become visible to everyone."><input type="hidden" name="id" value={dossier.id} /><button className="admin-button" type="submit">Publish</button></ConfirmForm>}<ConfirmForm action={deleteDossier} message="Delete this dossier permanently? This cannot be undone."><input type="hidden" name="id" value={dossier.id} /><button className="admin-button secondary" type="submit">Delete</button></ConfirmForm></div></div>) : <p className="empty-state">No dossiers match these filters.</p>}</div></main>;
}
